version: "3.8"

services:
  db:
    image: postgres:15
    container_name: rbac-db
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rbac-app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  postgres-data:
